# Generated by Django 5.1.1 on 2024-10-01 11:14

import app.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=app.models.get_expiry_time)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('companyName', models.CharField(max_length=255)),
                ('mailingAddress', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('yearOfEstablishment', models.IntegerField()),
                ('registrationNumber', models.CharField(max_length=20)),
                ('numberOfFarms', models.IntegerField()),
                ('preferredLanguage', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('fullName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('preferredLanguage', models.CharField(max_length=50)),
                ('nationalId', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('totalFarmArea', models.FloatField()),
                ('numberOfBlocks', models.IntegerField()),
                ('mainCropsGrown', models.CharField(max_length=255)),
                ('irrigationSystem', models.CharField(max_length=255)),
                ('averageAnnualRainfall', models.FloatField()),
                ('majorChallengesFaced', models.TextField()),
                ('farmEquipmentOwned', models.TextField()),
                ('farmLatitudeCoordinates', models.FloatField()),
                ('farmLongitudeCoordinates', models.FloatField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.farmer')),
            ],
        ),
    ]
