# Generated by Django 5.1.1 on 2024-10-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmingMethods',
            field=models.CharField(default='Traditional', max_length=255),
        ),
        migrations.AddField(
            model_name='farm',
            name='soilType',
            field=models.CharField(default='Loamy', max_length=255),
        ),
    ]
